### ISSUE TITLE
Add a shell to the image

### ISSUE THREAD

**Issue by stgrace** [coreos/fcct#82]
When using fcct in a GitLab pipeline to transpile the ignition config, you require a shell.
It would be nice if the default fcct image had a shell, or if another image would be provided with a shell.

**Comment by lucab** [comment]
Thanks for the report. We generally try not to put external things in container images unless required, in order to ease maintenance. However, a question about this:

> in a GitLab pipeline [...] you require a shell.

I'm not very familiar with GitLab pipeline, can you reference the doc where this requirement is coming from? I'm a bit surprised as CI executors generally take a plain command-line (i.e. without explicitly dictating a specific kind of shell).

**Comment by stgrace** [comment]
Hey Luca,

Thanks for a quick reply. 
Every job in GitLab-ci needs a required `script` keyword, which is always a shell script.
You can find the documentation here: https://docs.gitlab.com/ee/ci/yaml/#script

On this page they also mention a shell is required: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-a-docker-image-with-kaniko

**Comment by lucab** [comment]
@stgrace thanks for the links. Clicking through the docs I found where they actually describe how the Docker runner works (tldr: it attaches to a container and runs a new shell, piping tests to its stdin): https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image.

**Comment by jlebon** [comment]
Even if it had bash, the fcct image is likely to be missing other things you might need for testing. Can you use a more generic image and just dynamically download and verify fcct?

**Comment by jamescassell** [comment]
Indeed, you can use Fedora as a base image and add fcct with yum.

**Comment by lucab** [comment]
@jlebon I think the implicit request was for us to use `busybox` (or similar minimal image) as the base instead of `scratch`. I'm not opposed to that, just not thrilled. The alternative would be CI users maintaining their own images as multi-stage builds with busybox+fcct.

**Comment by jlebon** [comment]
Not a fan either. :)

> The alternative would be CI users maintaining their own images as multi-stage builds with busybox+fcct.

Right, but what I mean is that normally in a CI context you'd want more deps anyway depending on what you're testing. If it's very few deps that make building an image too much overhead, you can just install it on-the-fly. I'm not sure if GitLab runs containers as root, but if so, one can `dnf install fcct` at least. Otherwise, you can always pull the binary and signature directly from GitHub.

**Comment by bgilbert** [comment]
It seems like there's a rough consensus against this.  I'll close for now.  If there's any additional info we should have, feel free to comment here.
